### ISSUE TITLE
Sur Explorer (windows) le CTA sticky n'apparaît pas à l'arrivée sur la LP mais au scroll

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#11]
=> possible de le faire apparaître dès l'arrivée comme sur les autres navigateurs ?

**Comment by gregoirebiendine** [comment]
Sur Internet Explorer ou Edge ?

**Comment by romanebachelot** [comment]
@gregoirebiendine sur edge pardon (partout où j'ai dit explorer c'est edge dsl)

**Comment by gregoirebiendine** [comment]
D'acc merci, en quelle résolution ? Parce que c'est vraiment bizarre comme bug sachant que chez moi ca fonctionne :/

**Comment by romanebachelot** [comment]
@gregoirebiendine en fait c'est en 1280x1024 où on a le souci que tout se met au format mobile et le CTA se met en bas, c'est pas propre à edge (j'ai rechecké sur les autres résolutions c'est good)
