### ISSUE TITLE
Résolution 1920 x 1080 : grand espace vide à droite du carroussel => à voir si possible de résoudre

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#13]
En grande résolution sur tous navigateurs, il y a un grand espace vide à droite du carroussel 
![Capture d’écran 2024-04-03 à 11 03 27](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/c3bc114e-d2b8-4dd3-9f50-742213334998)

=> Pas grave si difficile à résoudre (ça reste lisible)

**Comment by gregoirebiendine** [comment]
Je peux soit :
- Laisser le texte aller un peu plus a droite (mais ducoup la hauteur ne sera pas remplie)
- Essayer de center tout le contenu (photo + texte)

**Comment by romanebachelot** [comment]
@gregoirebiendine tu peux tout centrer sans que ça casse l'affichage sur les autres résolutions?

**Comment by gregoirebiendine** [comment]
@romanebachelot je pense oui ça devrait passer
