### ISSUE TITLE
Mobile - le CTA du header n'apparaît qu'au scroll (et après avoir passé le header)

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#14]
![IMG_5832](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/1d232357-2130-48fd-b144-814d6a1925fa)

**Comment by romanebachelot** [comment]
Supprimer l'animation d'affichage du header sur mobile si c'est ça qui bloque (c'est pas indispensable sur mobile)

**Comment by gregoirebiendine** [comment]
Ah d'acc j'avais pas compris que le CTA sticky remplacait le CTA du header sur mobile, je change ça

**Comment by gregoirebiendine** [comment]
![image](https://github.com/romanebachelot/cimade-ifi24/assets/60387414/2acba092-3360-47ff-9fb7-8c8f5475287a)
Ca va pas faire un peu haut pour le CTA sticky sur le reste de la page ?

**Comment by romanebachelot** [comment]
@gregoirebiendine yes le cta sticky remplace le cta du header, mais là le cta du header (et du coup le sticky) met du temps à arriver, on ne l'a pas direct en ouvrant la lp
