### ISSUE TITLE
Sur mobile (à l'exception des Pixels) : possible d'ajouter un tout petit peu de marges à gauche et droit sur bloc IFI/IR ?

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#16]
Actuellement sur tous mobiles c'est très collé aux bords 
![Capture d’écran 2024-04-03 à 11 31 43](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/9933adb9-a5f6-4a3d-87c3-424a4a3f0d6c)

**Comment by gregoirebiendine** [comment]
Est ce que je peux avoir un modèle précis et le navigateur utilisé stp ?

**Comment by romanebachelot** [comment]
@gregoirebiendine iphone 12 safari : ![IMG_5834](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/a8ce2c72-655a-4eec-bf7e-e758d6e79f61)

Samsung S23, Chrome 
![Capture d’écran 2024-04-03 à 13 07 30](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/b5bbbcb8-b9a9-4095-8a14-54f5cebe4f43)

Samsung S24, Samsung Interner 
![Capture d’écran 2024-04-03 à 13 08 41](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/0751b2e7-6ddd-4136-880a-47e5842ab787)

Samsuns S22 Mozilla firefox
![Capture d’écran 2024-04-03 à 13 11 04](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/f4e83643-57ef-4f41-9036-7f993ed1dca9)
