### ISSUE TITLE
Visuel caroussel 1

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#6]
Le visuel est assez pixelisé, je te mets en PJ l'original, est-ce que tu peux résoudre ça, par exemple en floutant (ou je passe pas la créa ?)
![Evacuation084e-e1456936564802](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/587033df-1fce-4ddf-b3b7-4b3a616a8525)

**Comment by gregoirebiendine** [comment]
J'ai essayé un truc, c'est mieux ou pas ?
