### ISSUE TITLE
Les pictos sont coupés sur safari

### ISSUE THREAD

**Issue by romanebachelot** [romanebachelot/cimade-ifi24#7]
![Capture d’écran 2024-04-03 à 10 17 09](https://github.com/romanebachelot/cimade-ifi24/assets/150721648/74f586f1-d211-4c7d-a7e4-8fce5cafa304)

**Comment by gregoirebiendine** [comment]
Quel appareil et quelle version ?

**Comment by romanebachelot** [comment]
@gregoirebiendine sur les "anciennes versions" => iphone 11 à 13 et sur mac Monterey et en dessous (Safari 15.6)
